FROM node:alpine
WORKDIR /app

ARG PORT=3469
ARG FILES_DIR=/appender
ARG MAX_SUBFOLDERS=15
ARG MAX_APPEND_LENGTH=255
ARG WRITE_LIMIT_PERIOD=600000
ARG WRITE_LIMIT=10


COPY package.json ./
COPY yarn.lock ./
RUN yarn install

COPY . .

ENV PORT ${PORT}
ENV MAX_SUBFOLDERS ${MAX_SUBFOLDERS}
ENV MAX_APPEND_LENGTH ${MAX_APPEND_LENGTH}
ENV WRITE_LIMIT_PERIOD ${WRITE_LIMIT_PERIOD}
ENV WRITE_LIMIT ${WRITE_LIMIT}

EXPOSE ${PORT}
CMD [ "yarn", "start" ]